//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionEvaluationResult) DeepCopyInto(out *ConditionEvaluationResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionEvaluationResult.
func (in *ConditionEvaluationResult) DeepCopy() *ConditionEvaluationResult {
	if in == nil {
		return nil
	}
	out := new(ConditionEvaluationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionRequirement) DeepCopyInto(out *ConditionRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionRequirement.
func (in *ConditionRequirement) DeepCopy() *ConditionRequirement {
	if in == nil {
		return nil
	}
	out := new(ConditionRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DryRunResults) DeepCopyInto(out *DryRunResults) {
	*out = *in
	if in.AffectedNodes != nil {
		in, out := &in.AffectedNodes, &out.AffectedNodes
		*out = new(int32)
		**out = **in
	}
	if in.TaintsToAdd != nil {
		in, out := &in.TaintsToAdd, &out.TaintsToAdd
		*out = new(int32)
		**out = **in
	}
	if in.TaintsToRemove != nil {
		in, out := &in.TaintsToRemove, &out.TaintsToRemove
		*out = new(int32)
		**out = **in
	}
	if in.RiskyOperations != nil {
		in, out := &in.RiskyOperations, &out.RiskyOperations
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DryRunResults.
func (in *DryRunResults) DeepCopy() *DryRunResults {
	if in == nil {
		return nil
	}
	out := new(DryRunResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEvaluation) DeepCopyInto(out *NodeEvaluation) {
	*out = *in
	if in.ConditionResults != nil {
		in, out := &in.ConditionResults, &out.ConditionResults
		*out = make([]ConditionEvaluationResult, len(*in))
		copy(*out, *in)
	}
	in.LastEvaluationTime.DeepCopyInto(&out.LastEvaluationTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEvaluation.
func (in *NodeEvaluation) DeepCopy() *NodeEvaluation {
	if in == nil {
		return nil
	}
	out := new(NodeEvaluation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeFailure) DeepCopyInto(out *NodeFailure) {
	*out = *in
	in.LastEvaluationTime.DeepCopyInto(&out.LastEvaluationTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeFailure.
func (in *NodeFailure) DeepCopy() *NodeFailure {
	if in == nil {
		return nil
	}
	out := new(NodeFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReadinessRule) DeepCopyInto(out *NodeReadinessRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReadinessRule.
func (in *NodeReadinessRule) DeepCopy() *NodeReadinessRule {
	if in == nil {
		return nil
	}
	out := new(NodeReadinessRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeReadinessRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReadinessRuleList) DeepCopyInto(out *NodeReadinessRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeReadinessRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReadinessRuleList.
func (in *NodeReadinessRuleList) DeepCopy() *NodeReadinessRuleList {
	if in == nil {
		return nil
	}
	out := new(NodeReadinessRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeReadinessRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReadinessRuleSpec) DeepCopyInto(out *NodeReadinessRuleSpec) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionRequirement, len(*in))
		copy(*out, *in)
	}
	in.Taint.DeepCopyInto(&out.Taint)
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReadinessRuleSpec.
func (in *NodeReadinessRuleSpec) DeepCopy() *NodeReadinessRuleSpec {
	if in == nil {
		return nil
	}
	out := new(NodeReadinessRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReadinessRuleStatus) DeepCopyInto(out *NodeReadinessRuleStatus) {
	*out = *in
	if in.HeldNodes != nil {
		in, out := &in.HeldNodes, &out.HeldNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedNodes != nil {
		in, out := &in.FailedNodes, &out.FailedNodes
		*out = make([]NodeFailure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.DryRunResults.DeepCopyInto(&out.DryRunResults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReadinessRuleStatus.
func (in *NodeReadinessRuleStatus) DeepCopy() *NodeReadinessRuleStatus {
	if in == nil {
		return nil
	}
	out := new(NodeReadinessRuleStatus)
	in.DeepCopyInto(out)
	return out
}
